In [16]:
import numpy as np

In [6]:
input_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(input_list, type(input_list))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]] <class 'list'>


#### Create a numpy array from an iterable

In [30]:
numpy_array = np.array(input_list)
print(numpy_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Getting shape and type of data

In [11]:
print(numpy_array.shape, numpy_array.dtype)

(3, 3) int32


#### Basic matrix operations 

In [14]:
print(numpy_array * 2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [15]:
numpy_array_2 = np.array(input_list)
print(numpy_array + numpy_array_2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [20]:
print((numpy_array > 3) & (numpy_array < 5))

[[False False False]
 [ True False False]
 [False False False]]


#### Getting values from a matrix

In [31]:
print("row 0:", numpy_array[0])
print("row 0, column 1:", numpy_array[0, 1])
print("column 0:", numpy_array[:, 0]) 
print("row 0:", numpy_array[0, :])

row 0: [1 2 3]
row 0, column 1: 2
column 0: [1 4 7]
row 0: [1 2 3]
